### ISSUE TITLE
Settings.json requires doubleslashes

### ISSUE THREAD

**Issue by Lewko6702** [LargestBoi/AvatarLogger-GUI#3]
anybody not using a program that automatically changes \ to doubleslash(im too tired for this) will get a json error when inputting it into the settings json and is confusing to those who have never had the mod or this type of issue before 

![pain](https://user-images.githubusercontent.com/45269833/129819557-6c626f8d-d710-4c88-a0b1-68cc237a8b3b.PNG)

just thought i'd let you know 👍

**Comment by cassell1337** [comment]
jokes on you, you dont need to set them just use the installer kek im just teasing but use the installer ti set up things but thanks for the info
