### ISSUE TITLE
Lots of license violations!

### ISSUE THREAD

**Issue by skatinglasagna** [LargestBoi/AvatarLogger-GUI#5]
You have several license violations in this repo.

When you are shipping binaries, you also need to include their licenses and credit them in your e.g. README.

Files that violate licenses:
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/AssetsTools.NET.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/LZ4.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/MelonLoader.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/Mono.Cecil.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/Mono.Cecil.Rocks.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/Mono.Cecil.Pdb.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/Mono.Cecil.Mdb.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/SixLabors.ImageSharp.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/UnhollowerBaseLib.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/HOTSWAP/HOTSWAP/DLLs/librsync.net.dll

There are more than those listed above.
Your builds also contain binaries that are shipped without their respective licenses.

Builds:
https://github.com/LargestBoi/AvatarLogger-GUI/tree/main/AvatarLogger-master/bin/Release
https://github.com/LargestBoi/AvatarLogger-GUI/tree/main/AvatarLogger-master/bin/Debug

**Comment by LargestBoi** [comment]
I was unaware an extra packages required licenses to be published with the product as I believed the credits on the GitHub were enough, I will promptly add the license files for these dll files within a folder on the main branch that will be constantly updated. We thank you to bringing this to our attention, the issue will be closed once we have attached the correct licenses.

**Comment by LargestBoi** [comment]
> There are more than those listed above.
We have added licenses for the dlls provided, are there any that were missed? Our release builds will be updated once you have ensured no licenses have been missed.

**Comment by skatinglasagna** [comment]
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/AvatarLogger-master/bin/Release/Iced.dll
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/AvatarLogger-master/bin/Release/Newtonsoft.Json.dll (if non-il2cpp)
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/AvatarLogger-master/bin/Release/Facepunch.Steamworks.Win64.dll (if non-il2cpp)
https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/AvatarLogger-master/bin/Release/websocket-sharp.dll (if non-il2cpp)

Your LZ4 license is incorrect. It's shipped under BSD-2 (https://github.com/MiloszKrajewski/lz4net/blob/master/LICENSE.md)

**Comment by LargestBoi** [comment]
I could not locate the license for the following resources:

>https://github.com/LargestBoi/AvatarLogger-GUI/blob/main/AvatarLogger-master/bin/Release/Iced.dll

Could you assist me by locating it as I have failed to, besides this I have already implemented the changes you have requested in our "LICENCE V2" commit to our main branch.

**Comment by MistressPlague** [comment]
To add; ReMod.Core is no-license [Information](https://choosealicense.com/no-permission/) I would contact Requi and make sure you have rights to use it, or ask them to attach a license.

**Comment by MistressPlague** [comment]
I hate GitHub's new design so much.

**Comment by MistressPlague** [comment]
ReMod's license isn't in /LICENSE/ Btw.

**Comment by LargestBoi** [comment]
All is resolved, Imma lock this issue nows
